spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Fakon4565

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt_secret:
  somethingverymarvelouslong